### ISSUE TITLE
Vorsicht mit dem File index.html

### ISSUE THREAD

**Issue by martinchristen** [FredrikLennstroem/UebungenHS2022#1]
Sie haben das File index.html mit einem Grossbuchstaben I begonnen: https://github.com/FredrikLennstroem/UebungenHS2022/blob/main/Uebung01/Index.html

Dies funktioniert auf Web Servern nicht. Bitte umbenennen zu "index.html"

**Comment by FredrikLennstroem** [comment]
Sollte jetzt umbenannt sein

**Comment by martinchristen** [comment]
ist jetzt gut
https://htmlpreview.github.io/?https://github.com/FredrikLennstroem/UebungenHS2022/blob/master/Uebung01/index.html

Issue wird geschlossen 👍
